[package]
name = "spatio-scripts"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "generate_benchmarks"
path = "generate_benchmarks.rs"

[[bin]]
name = "create_sample_results"
path = "create_sample_results.rs"

[dependencies]
# No external dependencies needed for simple benchmark parsing
