name: Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: docs-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build documentation
        run: cargo doc --no-deps --document-private-items

      - name: Add index.html redirect
        run: |
          echo '<meta http-equiv="refresh" content="0; url=spatio">' > target/doc/index.html

      - name: Setup Pages
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

      - name: Deploy to GitHub Pages
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        id: deployment
        uses: actions/deploy-pages@v4

  validate:
    name: Validate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Test documentation examples
        run: cargo test --doc

      - name: Check documentation builds
        run: cargo doc --no-deps
